nexus:
  build: ./nexus
  ports:
    - 8081:8081

jenkins:
  build: ./jenkins
  ports:
    - "8080:8080"
  links:
    - nexus:nexus
    - gitlab:gitlab
    - sonar:sonar
    - selhub:hub
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/local/bin/docker:/usr/bin/docker

sonar:
  image: webdizz/sonarqube:5.1.2
  ports:
    - 9000:9000
    - 5432:5432
  environment:
    - SONAR_JDBC_URL=jdbc:postgresql://localhost:5432/sonar
db:
  image: postgres
  net: container:sonar
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar

# selhub:
#   image: selenium/hub
#   ports:
#     - 4444:4444

# nodeff:
#   image: selenium/node-firefox-debug
#   ports:
#     - 5900
#   links:
#     - selhub:hub

# nodechrome:
#   image: selenium/node-chrome-debug
#   ports:
#     - 5900
#   links:
#     - selhub:hub

postgresql:
  image: sameersbn/postgresql:9.4-3
  environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
  volumes:
    - /srv/docker/gitlab/postgresql:/var/lib/postgresql

gitlab:
  image: sameersbn/gitlab:8.3.2
  links:
    - redis:redisio
    - postgresql:postgresql
  ports:
    - "10080:80"
    - "10022:22"
  environment:
    - TZ=Europe/Berlin
    - GITLAB_TIMEZONE=Berlin

    - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string

    - GITLAB_HOST=localhost
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022

    - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
    - GITLAB_NOTIFY_PUSHER=false

    - GITLAB_EMAIL=no-reply@datarx.cn
    - GITLAB_EMAIL_REPLY_TO=no-reply@datarx.cn
    - GITLAB_INCOMING_EMAIL_ADDRESS=no-reply@datarx.cn

    - GITLAB_BACKUPS=daily
    - GITLAB_BACKUP_TIME=01:00

    - SMTP_ENABLED=false
    - SMTP_DOMAIN=www.mxhichina.com
    - SMTP_HOST=smtp.mxhichina.com
    - SMTP_PORT=465
    - SMTP_USER=no-reply@datarx.cn
    - SMTP_PASS=DataRx2016
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login

    - IMAP_ENABLED=false
    - IMAP_HOST=imap.mxhichina.com
    - IMAP_PORT=993
    - IMAP_USER=no-reply@datarx.cn
    - IMAP_PASS=DataRx2016
    - IMAP_SSL=true
    - IMAP_STARTTLS=false
  volumes:
    - /srv/docker/gitlab/gitlab:/home/git/data
redis:
  image: sameersbn/redis:latest
  volumes:
    - /srv/docker/gitlab/redis:/var/lib/redis

registry:
  image: registry
  volumes:
    - /var/lib/docker/registry:/var/lib/docker/registry
  ports:
    - 5000:5000
