nexus:
  build: ./nexus
  ports:
    - 8081:8081

jenkins:
  build: ./jenkins
  ports:
    - "8080:8080"
  links:
    - nexus:nexus
    - gitlab:gitlab
    - sonar:sonar
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/local/bin/docker:/usr/bin/docker

sonar:
  image: webdizz/sonarqube:5.1.2
  ports:
    - 9000:9000
    - 5432:5432
  environment:
    - SONAR_JDBC_URL=jdbc:postgresql://localhost:5432/sonar
db:
  image: postgres
  net: container:sonar
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar

postgresql:
  image: sameersbn/postgresql:9.4-3
  environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
  volumes:
    - /srv/docker/gitlab/postgresql:/var/lib/postgresql

gitlab:
  image: sameersbn/gitlab:8.3.2
  links:
    - redis:redisio
    - postgresql:postgresql
  ports:
    - "10080:80"
    - "10022:22"
  environment:
    - GITLAB_TIMEZONE=Asia/Shanghai
    - GITLAB_SECRETS_DB_KEY_BASE=c678a29e-ea62-11e5-a669-442a60db842f

    - GITLAB_HOST=localhost
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022

    - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
    - GITLAB_NOTIFY_PUSHER=false

    - GITLAB_EMAIL=no-reply@datarx.cn
    - GITLAB_EMAIL_REPLY_TO=no-reply@datarx.cn
    - GITLAB_INCOMING_EMAIL_ADDRESS=no-reply@datarx.cn

    - GITLAB_BACKUPS=daily
    - GITLAB_BACKUP_TIME=01:00

    - SMTP_DOMAIN=www.mxhichina.com
    - SMTP_HOST=smtp.mxhichina.com
    - SMTP_PORT=465
    - SMTP_USER=no-reply@datarx.cn
    - SMTP_PASS=DataRx2016
    - SMTP_AUTHENTICATION=login

    - IMAP_HOST=imap.mxhichina.com
    - IMAP_PORT=993
    - IMAP_USER=no-reply@datarx.cn
    - IMAP_PASS=DataRx2016
  volumes:
    - /srv/docker/gitlab/gitlab:/home/git/data
  restart: always

redis:
  image: sameersbn/redis:latest
  volumes:
    - /srv/docker/gitlab/redis:/var/lib/redis
  restart: always

nginx:
  image: "nginx:latest"
  links:
    - registry
    - jenkins
    - nexus
    - gitlab
  ports:
    - "9443:443"
  volumes:
    - "./nginx/nginx.conf:/etc/nginx/conf.d/docker-registry.conf:ro"
    - "./nginx/docker-registry.key:/etc/nginx/docker-registry.key:ro"
    - "./nginx/docker-registry.crt:/etc/nginx/docker-registry.crt:ro"
    - "./nginx/docker-registry.conf:/etc/nginx/docker-registry.conf:ro"
    - "./nginx/docker-registry.htpasswd:/etc/nginx/docker-registry.htpasswd:ro"
  restart: always

registry:
  environment:
    CACHE_REDIS_HOST: redis
    CACHE_REDIS_PORT: 6379
    SEARCH_BACKEND: sqlalchemy
    SETTINGS_FLAVOR: local
    SQLALCHEMY_INDEX_DATABASE: "sqlite:////var/docker-registry-storage/docker-registry.db"
    STORAGE_PATH: /var/docker-registry-storage
  image: "registry:latest"
  restart: always
  links:
    - redis
  volumes:
    - "/var/docker-registry-storage:/var/docker-registry-storage"
